"""Initial migration

Revision ID: 5a6b0db8aac9
Revises: fd78a5a67719
Create Date: 2026-05-06 22:59:35.757641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6b0db8aac9'
down_revision: Union[str, Sequence[str], None] = 'fd78a5a67719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('warna', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_index(op.f('ix_kategori_slug'), 'kategori', ['slug'], unique=True)
    op.create_table('komunitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('jumlah_anggota', sa.Integer(), nullable=True),
    sa.Column('link_whatsapp', sa.String(length=500), nullable=True),
    sa.Column('warna', sa.String(length=50), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komunitas_id'), 'komunitas', ['id'], unique=False)
    op.create_index(op.f('ix_komunitas_slug'), 'komunitas', ['slug'], unique=True)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.String(length=50), nullable=True),
    sa.Column('penulis_nama', sa.String(length=150), nullable=False),
    sa.Column('penulis_daerah', sa.String(length=150), nullable=True),
    sa.Column('judul', sa.String(length=300), nullable=False),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('kategori', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('catatan_kurator', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('judul', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('author_initial', sa.String(length=10), nullable=True),
    sa.Column('author_role', sa.String(length=150), nullable=True),
    sa.Column('daerah', sa.String(length=150), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('menit_baca', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=100), nullable=True),
    sa.Column('image_color', sa.String(length=50), nullable=True),
    sa.Column('diterbitkan', sa.Boolean(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artikel_id'), 'artikel', ['id'], unique=False)
    op.create_index(op.f('ix_artikel_slug'), 'artikel', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artikel_slug'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_id'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_komunitas_slug'), table_name='komunitas')
    op.drop_index(op.f('ix_komunitas_id'), table_name='komunitas')
    op.drop_table('komunitas')
    op.drop_index(op.f('ix_kategori_slug'), table_name='kategori')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
