"""perbaikan tabel

Revision ID: b48cbf4df5f6
Revises: a3a435d6edf1
Create Date: 2026-05-06 21:11:35.848866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b48cbf4df5f6'
down_revision: Union[str, Sequence[str], None] = 'a3a435d6edf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_komunitas_id'), table_name='komunitas')
    op.drop_table('komunitas')
    op.drop_index(op.f('ix_artikel_id'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_slug'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_index(op.f('ix_kategori_slug'), table_name='kategori')
    op.drop_table('kategori')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('notes')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('daerah', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('menit_baca', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diterbitkan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kategori_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], name=op.f('articles_kategori_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('articles_pkey'))
    )
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('penulis_nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('penulis_daerah', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('judul', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('konten', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kategori_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('catatan_kurator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], name=op.f('submissions_kategori_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submissions_pkey'))
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('kategori',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kategori_pkey'))
    )
    op.create_index(op.f('ix_kategori_slug'), 'kategori', ['slug'], unique=True)
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('artikel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('judul', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('author_initial', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('author_role', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('daerah', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('menit_baca', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('diterbitkan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kategori_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], name=op.f('artikel_kategori_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artikel_pkey'))
    )
    op.create_index(op.f('ix_artikel_slug'), 'artikel', ['slug'], unique=True)
    op.create_index(op.f('ix_artikel_id'), 'artikel', ['id'], unique=False)
    op.create_table('komunitas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('moderator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jumlah_anggota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_whatsapp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('komunitas_pkey'))
    )
    op.create_index(op.f('ix_komunitas_id'), 'komunitas', ['id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipe', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('penulis_nama', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('penulis_daerah', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('judul', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('konten', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kategori', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('catatan_kurator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_pkey'))
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    # ### end Alembic commands ###
