"""restart all over again

Revision ID: d8eee3e15f75
Revises: dc5d013237a8
Create Date: 2026-05-07 13:18:25.903752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8eee3e15f75'
down_revision: Union[str, Sequence[str], None] = 'dc5d013237a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artikel_komunitas_id_fkey'), 'artikel', type_='foreignkey')
    op.drop_column('artikel', 'komunitas_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artikel', sa.Column('komunitas_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('artikel_komunitas_id_fkey'), 'artikel', 'komunitas', ['komunitas_id'], ['id'])
    # ### end Alembic commands ###
