"""add slug to komunitas

Revision ID: dc5d013237a8
Revises: 5a6b0db8aac9
Create Date: 2026-05-07 10:10:14.918627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5d013237a8'
down_revision: Union[str, Sequence[str], None] = '5a6b0db8aac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artikel', 'komunitas', ['komunitas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artikel', type_='foreignkey')
    # ### end Alembic commands ###
